language: bash

os: 
  - linux
  - osx
  - windows

arch:
  - amd64

env:
  - DEDICATED=true
  - DEDICATED=false

matrix:
  exclude:
    - os: osx
      arch: x86_64

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$TRAVIS_ARCH" == "amd64" ]]; then
        if [[ "$DEDICATED" == "true" ]]; then
          scripts/build-ubuntu-amd64.sh -d
        else
          scripts/build-ubuntu-amd64.sh
        fi
      fi

    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      powershell -Command "
        if ('$TRAVIS_ARCH' -eq 'amd64') {
          if ('$DEDICATED' -eq 'true') {
            ./waf.bat configure -T debug -d
          } else {
            ./waf.bat configure -T debug
          }
        }
        ./waf.bat build
      "

    elif [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_ARCH" == "amd64" ]]; then
      if [[ "$DEDICATED" == "true" ]]; then
        scripts/build-macos-amd64.sh -d
      else
        scripts/build-macos-amd64.sh
      fi
    fi
